"""Write OCR, translation, Markdown, and optional Word artifacts."""

from __future__ import annotations

from pathlib import Path

from .utils import ensure_dir


class OutputWriteError(RuntimeError):
    """Raised when result files cannot be written."""


class OutputWriter:
    """Persist pipeline results as UTF-8 text and a simple Word document."""

    def __init__(self, output_dir: Path) -> None:
        self.output_dir = ensure_dir(output_dir)

    def write_all(self, source_pdf: Path, ocr_text: str, translated_text: str) -> dict[str, Path]:
        """Write required artifacts and return their paths."""
        paths = {
            "ocr_raw": self.output_dir / "ocr_raw.txt",
            "translated_txt": self.output_dir / "translated.txt",
            "translated_md": self.output_dir / "translated.md",
        }
        markdown = (
            "# PDF OCR Translation Result\n\n"
            f"Source PDF: `{source_pdf.name}`\n\n"
            "Generated by: PDF OCR DeepSeek Translator\n\n"
            "---\n\n"
            "## OCR Raw Text\n\n"
            "完整 OCR 原文请查看同目录下的 `ocr_raw.txt`。\n\n"
            "---\n\n"
            "## Chinese Translation\n\n"
            f"{translated_text.strip()}\n"
        )
        try:
            paths["ocr_raw"].write_text(ocr_text.rstrip() + "\n", encoding="utf-8")
            paths["translated_txt"].write_text(translated_text.rstrip() + "\n", encoding="utf-8")
            paths["translated_md"].write_text(markdown, encoding="utf-8")
        except OSError as exc:
            raise OutputWriteError(f"无法写入输出目录 {self.output_dir}：{exc}") from exc

        docx_path = self._write_docx(source_pdf, translated_text)
        if docx_path:
            paths["translated_docx"] = docx_path
        return paths

    def _write_docx(self, source_pdf: Path, translated_text: str) -> Path | None:
        """Generate translated.docx when python-docx is importable."""
        try:
            from docx import Document
        except ImportError:
            return None

        path = self.output_dir / "translated.docx"
        try:
            document = Document()
            document.add_heading("PDF OCR Translation Result", level=0)
            document.add_paragraph(f"Source PDF: {source_pdf.name}")
            document.add_paragraph("Generated by: PDF OCR DeepSeek Translator")
            document.add_heading("Chinese Translation", level=1)
            for block in translated_text.split("\n\n"):
                if block.strip():
                    document.add_paragraph(block.strip())
            document.save(path)
        except (OSError, ValueError) as exc:
            raise OutputWriteError(f"无法生成 Word 文件：{exc}") from exc
        return path
